import { Club, Event, User, Post } from './types';

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Alex Rivera',
  email: 'alex@example.com',
  avatar: 'https://picsum.photos/200',
  city: 'San Francisco',
  interests: ['Tech', 'Music', 'Design'],
  joinedClubs: ['c5', 'c20'],
};

export const MOCK_CLUBS: Club[] = [
  {
    id: 'c1',
    name: 'The Book Nook',
    description: 'Dive into worlds unknown. A sanctuary for bibliophiles to discuss classics and modern hits.',
    category: 'Books',
    memberCount: 1240,
    image: 'https://picsum.photos/seed/books/400/400',
    coverImage: 'https://picsum.photos/seed/books-cover/1200/400',
    tags: ['Fiction', 'Literature', 'Coffee'],
    members: [],
  },
  {
    id: 'c2',
    name: 'Mile High Run Club',
    description: 'Pacing together towards better health. Whether 5K or Marathon, we run as one.',
    category: 'Running',
    memberCount: 850,
    image: 'https://picsum.photos/seed/run/400/400',
    coverImage: 'https://picsum.photos/seed/run-cover/1200/400',
    tags: ['Marathon', 'Jogging', 'Health'],
    members: [],
  },
  {
    id: 'c3',
    name: 'Fretboard Warriors',
    description: 'For those about to rock. Jam sessions, theory workshops, and gig nights.',
    category: 'Music',
    memberCount: 620,
    image: 'https://picsum.photos/seed/guitar/400/400',
    coverImage: 'https://picsum.photos/seed/guitar-cover/1200/400',
    tags: ['Guitar', 'Band', 'Live'],
    members: [],
  },
  {
    id: 'c4',
    name: 'Iron Paradise',
    description: 'Forging strength through discipline. Weightlifting, calisthenics, and nutrition.',
    category: 'Fitness',
    memberCount: 2100,
    image: 'https://picsum.photos/seed/gym/400/400',
    coverImage: 'https://picsum.photos/seed/gym-cover/1200/400',
    tags: ['Gym', 'Weights', 'Cardio'],
    members: [],
  },
  {
    id: 'c5',
    name: 'Code & Coffee',
    description: 'Building the future, one line at a time. Hackathons, pair programming, and tech talks.',
    category: 'Tech',
    memberCount: 3400,
    image: 'https://picsum.photos/seed/code/400/400',
    coverImage: 'https://picsum.photos/seed/code-cover/1200/400',
    tags: ['Programming', 'Web', 'AI'],
    members: [],
  },
  {
    id: 'c6',
    name: 'Unicorn Founders',
    description: 'From idea to IPO. A network of ambitious entrepreneurs disrupting industries.',
    category: 'Startups',
    memberCount: 900,
    image: 'https://picsum.photos/seed/startup/400/400',
    coverImage: 'https://picsum.photos/seed/startup-cover/1200/400',
    tags: ['Business', 'Venture', 'Pitch'],
    members: [],
  },
  {
    id: 'c7',
    name: 'Lens & Light',
    description: 'Capturing moments that last forever. Photo walks, studio sessions, and critiques.',
    category: 'Photography',
    memberCount: 1100,
    image: 'https://picsum.photos/seed/photo/400/400',
    coverImage: 'https://picsum.photos/seed/photo-cover/1200/400',
    tags: ['DSLR', 'Portrait', 'Landscape'],
    members: [],
  },
  {
    id: 'c8',
    name: 'Wanderlust Souls',
    description: 'Exploring the globe. Backpacking tips, travel buddies, and cultural exchange.',
    category: 'Travel',
    memberCount: 4500,
    image: 'https://picsum.photos/seed/travel/400/400',
    coverImage: 'https://picsum.photos/seed/travel-cover/1200/400',
    tags: ['Adventure', 'Hiking', 'Culture'],
    members: [],
  },
  {
    id: 'c9',
    name: 'Cinema Society',
    description: 'More than just watching. Dissecting cinematography, scripts, and hidden meanings.',
    category: 'Movies',
    memberCount: 1300,
    image: 'https://picsum.photos/seed/movie/400/400',
    coverImage: 'https://picsum.photos/seed/movie-cover/1200/400',
    tags: ['Film', 'Critique', 'Hollywood'],
    members: [],
  },
  {
    id: 'c10',
    name: 'Graphite & Ink',
    description: 'Expressing the soul on canvas. Sketching, painting, and digital art workshops.',
    category: 'Art',
    memberCount: 780,
    image: 'https://picsum.photos/seed/art/400/400',
    coverImage: 'https://picsum.photos/seed/art-cover/1200/400',
    tags: ['Drawing', 'Painting', 'Creative'],
    members: [],
  },
  {
    id: 'c11',
    name: 'Whisk & Roll',
    description: 'Culinary masterpieces made at home. Recipe swaps, bake-offs, and tasting parties.',
    category: 'Cooking',
    memberCount: 1500,
    image: 'https://picsum.photos/seed/cook/400/400',
    coverImage: 'https://picsum.photos/seed/cook-cover/1200/400',
    tags: ['Food', 'Baking', 'Gourmet'],
    members: [],
  },
  {
    id: 'c12',
    name: 'Checkmate Lounge',
    description: 'Strategic minds collide. Tournaments, casual play, and grandmaster analysis.',
    category: 'Chess',
    memberCount: 500,
    image: 'https://picsum.photos/seed/chess/400/400',
    coverImage: 'https://picsum.photos/seed/chess-cover/1200/400',
    tags: ['Strategy', 'Board Games', 'Focus'],
    members: [],
  },
  {
    id: 'c13',
    name: 'Zen Circle',
    description: 'Finding peace in chaos. Guided meditation, yoga flows, and mindfulness retreats.',
    category: 'Wellness',
    memberCount: 2200,
    image: 'https://picsum.photos/seed/zen/400/400',
    coverImage: 'https://picsum.photos/seed/zen-cover/1200/400',
    tags: ['Meditation', 'Yoga', 'Peace'],
    members: [],
  },
  {
    id: 'c14',
    name: 'Chain Gang',
    description: 'Two wheels, endless roads. Weekend rides, hill climbs, and gear talk.',
    category: 'Cycling',
    memberCount: 950,
    image: 'https://picsum.photos/seed/bike/400/400',
    coverImage: 'https://picsum.photos/seed/bike-cover/1200/400',
    tags: ['Biking', 'Road', 'Speed'],
    members: [],
  },
  {
    id: 'c15',
    name: 'Rhythm Nation',
    description: 'Movement is life. Hip-hop, salsa, contemporary, and freestyle sessions.',
    category: 'Dance',
    memberCount: 1150,
    image: 'https://picsum.photos/seed/dance/400/400',
    coverImage: 'https://picsum.photos/seed/dance-cover/1200/400',
    tags: ['Choreography', 'Fun', 'Social'],
    members: [],
  },
  {
    id: 'c16',
    name: 'Otaku Haven',
    description: 'Celebrating Japanese culture. Manga reading, anime screenings, and cosplay.',
    category: 'Anime',
    memberCount: 3100,
    image: 'https://picsum.photos/seed/anime/400/400',
    coverImage: 'https://picsum.photos/seed/anime-cover/1200/400',
    tags: ['Manga', 'Cosplay', 'Japan'],
    members: [],
  },
  {
    id: 'c17',
    name: 'Bull & Bear',
    description: 'Mastering the markets. Stock analysis, crypto trends, and personal finance.',
    category: 'Finance',
    memberCount: 1800,
    image: 'https://picsum.photos/seed/money/400/400',
    coverImage: 'https://picsum.photos/seed/money-cover/1200/400',
    tags: ['Stocks', 'Investing', 'Wealth'],
    members: [],
  },
  {
    id: 'c18',
    name: 'Toastmasters Elite',
    description: 'Finding your voice. Public speaking practice, debates, and leadership skills.',
    category: 'Speaking',
    memberCount: 400,
    image: 'https://picsum.photos/seed/speak/400/400',
    coverImage: 'https://picsum.photos/seed/speak-cover/1200/400',
    tags: ['Leadership', 'Debate', 'Confidence'],
    members: [],
  },
  {
    id: 'c19',
    name: 'GG EZ',
    description: 'Competitive and casual gaming. Esports tournaments, LAN parties, and streams.',
    category: 'Gaming',
    memberCount: 5600,
    image: 'https://picsum.photos/seed/game/400/400',
    coverImage: 'https://picsum.photos/seed/game-cover/1200/400',
    tags: ['Esports', 'PC', 'Console'],
    members: [],
  },
  {
    id: 'c20',
    name: 'Pixel Perfect',
    description: 'Designing delightful experiences. UI/UX critiques, case studies, and prototyping.',
    category: 'Design',
    memberCount: 1400,
    image: 'https://picsum.photos/seed/uiux/400/400',
    coverImage: 'https://picsum.photos/seed/uiux-cover/1200/400',
    tags: ['UI', 'UX', 'Product'],
    members: [],
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: 'e1',
    clubId: 'c5',
    title: 'Late Night Hackathon',
    description: 'Bring your laptop and your best ideas. Pizza provided!',
    date: '2023-11-15T18:00:00',
    location: 'TechHub Downtown',
    attendees: 42,
  },
  {
    id: 'e2',
    clubId: 'c20',
    title: 'Design Critique Session',
    description: 'Get feedback on your portfolio from senior designers.',
    date: '2023-11-20T19:00:00',
    location: 'Creative Loft',
    attendees: 15,
  }
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'p1',
    clubId: 'c5',
    user: MOCK_USER,
    content: 'Just shipped my first React app! Thanks for the help everyone.',
    likes: 24,
    timestamp: '2 hours ago',
  }
];
