
import { Club, Event, User, Post, Notification } from './types';

export const TOP_CITIES = [
    "Mumbai", "Delhi NCR", "Bangalore", "Hyderabad", "Chennai"
];

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Alex Rivera',
  email: 'alex@example.com',
  avatar: 'https://picsum.photos/seed/u1/200',
  city: 'Bangalore',
  interests: ['Tech', 'Music', 'Design'],
  joinedClubs: ['c5', 'c20'],
};

export const MOCK_MEMBERS: User[] = Array.from({ length: 12 }).map((_, i) => ({
    id: `m${i}`,
    name: `Member ${i + 1}`,
    email: `member${i}@example.com`,
    avatar: `https://picsum.photos/seed/${i + 100}/200`,
    city: 'Mumbai',
    interests: [],
    joinedClubs: []
}));

export const MOCK_CLUBS: Club[] = [
  {
    id: 'c1',
    name: 'The Book Nook',
    description: 'Dive into worlds unknown. A sanctuary for bibliophiles to discuss classics and modern hits.',
    category: 'Books',
    memberCount: 1240,
    image: 'https://images.unsplash.com/photo-1610116306796-6fea9f4fae38',
    coverImage: 'https://images.unsplash.com/photo-1610116306796-6fea9f4fae38',
    tags: ['Fiction', 'Literature', 'Coffee'],
    members: [],
    visibility: 'public',
    location: 'Mumbai',
    ownerId: 'admin',
    founderName: 'Ananya Desai',
    founderBio: 'Believer in the magic of turning pages and changing lives.'
  },
  {
    id: 'c2',
    name: 'Run for Fun',
    description: 'Pacing together towards better health. Whether 5K or Marathon, we run as one.',
    category: 'Running',
    memberCount: 850,
    image: 'https://images.unsplash.com/photo-1502904550040-7534597429ae',
    coverImage: 'https://images.unsplash.com/photo-1502904550040-7534597429ae',
    tags: ['Marathon', 'Jogging', 'Health'],
    members: [],
    visibility: 'public',
    location: 'Bangalore',
    ownerId: 'admin',
    founderName: 'Vikram Singh',
    founderBio: 'Running is not just a sport, it is therapy for the soul.'
  },
  {
    id: 'c3',
    name: 'Rock Music Lovers',
    description: 'For those about to rock. Jam sessions, theory workshops, and gig nights.',
    category: 'Music',
    memberCount: 620,
    image: 'https://images.unsplash.com/photo-1546708770-589dab7b22c7',
    coverImage: 'https://images.unsplash.com/photo-1546708770-589dab7b22c7',
    tags: ['Guitar', 'Band', 'Live'],
    members: [],
    visibility: 'public',
    location: 'Delhi NCR',
    ownerId: 'u1',
    founderName: 'Rohan Das',
    founderBio: 'Amplifying emotions through strings, beats, and distortion.'
  },
  {
    id: 'c4',
    name: 'Fitness Freaks',
    description: 'Forging strength through discipline. Weightlifting, calisthenics, and nutrition.',
    category: 'Fitness',
    memberCount: 2100,
    image: 'https://images.unsplash.com/photo-1627483298606-cf54c61779a9',
    coverImage: 'https://images.unsplash.com/photo-1627483298606-cf54c61779a9',
    tags: ['Gym', 'Weights', 'Cardio'],
    members: [],
    visibility: 'public',
    location: 'Mumbai',
    ownerId: 'admin',
    founderName: 'Aryan Khanna',
    founderBio: 'Discipline is the bridge between goals and accomplishment.'
  },
  {
    id: 'c5',
    name: 'Crazy Coders',
    description: 'Building the future, one line at a time. Hackathons, pair programming, and tech talks.',
    category: 'Tech',
    memberCount: 3400,
    image: 'https://images.unsplash.com/photo-1698919585695-546e4a31fc8f',
    coverImage: 'https://images.unsplash.com/photo-1698919585695-546e4a31fc8f',
    tags: ['Programming', 'Web', 'AI'],
    members: [],
    visibility: 'public',
    location: 'Bangalore',
    ownerId: 'admin',
    founderName: 'Ishaan Gupta',
    founderBio: 'Turning caffeine into code and dreams into reality since 2015.'
  },
  {
    id: 'c6',
    name: 'Enthu Entrepreneurs',
    description: 'From idea to IPO. A network of ambitious entrepreneurs disrupting industries.',
    category: 'Startups',
    memberCount: 900,
    image: 'https://images.unsplash.com/photo-1554774853-aae0a22c8aa4',
    coverImage: 'https://images.unsplash.com/photo-1554774853-aae0a22c8aa4',
    tags: ['Business', 'Venture', 'Pitch'],
    members: [],
    visibility: 'private',
    location: 'Bangalore',
    ownerId: 'admin',
    founderName: 'Riya Sharma',
    founderBio: 'Empowering the next generation of disruptors to build what matters.'
  },
  {
    id: 'c7',
    name: 'Lens & Light',
    description: 'Capturing moments that last forever. Photo walks, studio sessions, and critiques.',
    category: 'Photography',
    memberCount: 1100,
    image: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e',
    coverImage: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e',
    tags: ['DSLR', 'Portrait', 'Landscape'],
    members: [],
    visibility: 'public',
    location: 'Delhi NCR',
    ownerId: 'admin',
    founderName: 'Kabir Bedi',
    founderBio: 'Capturing the world, one shutter click at a time.'
  },
  {
    id: 'c8',
    name: 'Wanderlust Souls',
    description: 'Exploring the globe. Backpacking tips, travel buddies, and cultural exchange.',
    category: 'Travel',
    memberCount: 4500,
    image: 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff',
    coverImage: 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff',
    tags: ['Adventure', 'Hiking', 'Culture'],
    members: [],
    visibility: 'public',
    location: 'Hyderabad',
    ownerId: 'admin',
    founderName: 'Zoya Akhtar',
    founderBio: 'Not all those who wander are lost, some are just exploring.'
  },
  {
    id: 'c9',
    name: 'Cinema Society',
    description: 'More than just watching. Dissecting cinematography, scripts, and hidden meanings.',
    category: 'Movies',
    memberCount: 1300,
    image: 'https://plus.unsplash.com/premium_photo-1710522706751-c2f0c76cc5fd',
    coverImage: 'https://plus.unsplash.com/premium_photo-1710522706751-c2f0c76cc5fd',
    tags: ['Film', 'Critique', 'Hollywood'],
    members: [],
    visibility: 'public',
    location: 'Mumbai',
    ownerId: 'admin',
    founderName: 'Arjun Mehta',
    founderBio: 'Cinema is a mirror to society, reflecting our deepest truths.'
  },
  {
    id: 'c10',
    name: 'Painting Passionates',
    description: 'Expressing the soul on canvas. Sketching, painting, and digital art workshops.',
    category: 'Art',
    memberCount: 780,
    image: 'https://images.unsplash.com/photo-1501084817091-a4f3d1d19e07',
    coverImage: 'https://images.unsplash.com/photo-1501084817091-a4f3d1d19e07',
    tags: ['Drawing', 'Painting', 'Creative'],
    members: [],
    visibility: 'public',
    location: 'Chennai',
    ownerId: 'admin',
    founderName: 'Mira Patel',
    founderBio: 'Colors speak louder than words ever could.'
  },
  {
    id: 'c11',
    name: 'Cake Bake',
    description: 'Culinary masterpieces made at home. Recipe swaps, bake-offs, and tasting parties.',
    category: 'Cooking',
    memberCount: 1500,
    image: 'https://plus.unsplash.com/premium_photo-1673525280962-c0febee54cfa',
    coverImage: 'https://plus.unsplash.com/premium_photo-1673525280962-c0febee54cfa',
    tags: ['Food', 'Baking', 'Gourmet'],
    members: [],
    visibility: 'public',
    location: 'Hyderabad',
    ownerId: 'admin',
    founderName: 'Sanjeev Verma',
    founderBio: 'Baking the world a better place, one cake at a time.'
  },
  {
    id: 'c12',
    name: 'Checkmate Lounge',
    description: 'Strategic minds collide. Tournaments, casual play, and grandmaster analysis.',
    category: 'Games',
    memberCount: 500,
    image: 'https://images.unsplash.com/photo-1705043859787-93d64c9e3c01',
    coverImage: 'https://images.unsplash.com/photo-1705043859787-93d64c9e3c01',
    tags: ['Strategy', 'Board Games', 'Focus'],
    members: [],
    visibility: 'public',
    location: 'Chennai',
    ownerId: 'admin',
    founderName: 'Vihaan Anand',
    founderBio: 'Life is like chess, make your move before time runs out.'
  },
  {
    id: 'c13',
    name: 'Meditation Gurus',
    description: 'Finding peace in chaos. Guided meditation, yoga flows, and mindfulness retreats.',
    category: 'Wellness',
    memberCount: 2200,
    image: 'https://images.unsplash.com/reserve/YEc7WB6ASDydBTw6GDlF_antalya-beach-lulu.jpg',
    coverImage: 'https://images.unsplash.com/reserve/YEc7WB6ASDydBTw6GDlF_antalya-beach-lulu.jpg',
    tags: ['Meditation', 'Yoga', 'Peace'],
    members: [],
    visibility: 'public',
    location: 'Bangalore',
    ownerId: 'admin',
    founderName: 'Deepak Sethi',
    founderBio: 'Stillness is the key to strength in a chaotic world.'
  },
  {
    id: 'c14',
    name: 'Chain Gang',
    description: 'Two wheels, endless roads. Weekend rides, hill climbs, and gear talk.',
    category: 'Cycling',
    memberCount: 950,
    image: 'https://images.unsplash.com/photo-1631276893368-554b60393efb',
    coverImage: 'https://images.unsplash.com/photo-1631276893368-554b60393efb',
    tags: ['Biking', 'Road', 'Speed'],
    members: [],
    visibility: 'public',
    location: 'Mumbai',
    ownerId: 'admin',
    founderName: 'Aditya Roy',
    founderBio: 'Life is like riding a bicycle, you must keep moving to find balance.'
  },
  {
    id: 'c15',
    name: 'Rhythm Nation',
    description: 'Movement is life. Hip-hop, salsa, contemporary, and freestyle sessions.',
    category: 'Dance',
    memberCount: 1150,
    image: 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e',
    coverImage: 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e',
    tags: ['Choreography', 'Fun', 'Social'],
    members: [],
    visibility: 'public',
    location: 'Mumbai',
    ownerId: 'admin',
    founderName: 'Shreya Iyer',
    founderBio: 'Dance is the hidden language of the soul.'
  },
  {
    id: 'c16',
    name: 'Anime Lovers',
    description: 'Celebrating Japanese culture. Manga reading, anime screenings, and cosplay.',
    category: 'Anime',
    memberCount: 3100,
    image: 'https://images.unsplash.com/photo-1601850494422-3cf14624b0b3',
    coverImage: 'https://images.unsplash.com/photo-1601850494422-3cf14624b0b3',
    tags: ['Manga', 'Cosplay', 'Japan'],
    members: [],
    visibility: 'public',
    location: 'Bangalore',
    ownerId: 'admin',
    founderName: 'Rahul Nair',
    founderBio: 'Dattebayo! Living the anime dream every single day.'
  },
  {
    id: 'c17',
    name: 'Bull & Bear',
    description: 'Mastering the markets. Stock analysis, crypto trends, and personal finance.',
    category: 'Finance',
    memberCount: 1800,
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3',
    coverImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3',
    tags: ['Stocks', 'Investing', 'Wealth'],
    members: [],
    visibility: 'private',
    location: 'Mumbai',
    ownerId: 'admin',
    founderName: 'Harish Mehta',
    founderBio: 'Compound interest is the eighth wonder of the world.'
  },
  {
    id: 'c18',
    name: 'Leading Legends',
    description: 'Finding your voice. Public speaking practice, debates, and leadership skills.',
    category: 'Speaking',
    memberCount: 400,
    image: 'https://images.unsplash.com/photo-1544531586-fde5298cdd40',
    coverImage: 'https://images.unsplash.com/photo-1544531586-fde5298cdd40',
    tags: ['Leadership', 'Debate', 'Confidence'],
    members: [],
    visibility: 'public',
    location: 'Delhi NCR',
    ownerId: 'admin',
    founderName: 'Shashi Nair',
    founderBio: 'Words have the power to change the world, use them wisely.'
  },
  {
    id: 'c19',
    name: 'Esports Gamers',
    description: 'Competitive and casual gaming. Esports tournaments, LAN parties, and streams.',
    category: 'Gaming',
    memberCount: 5600,
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e',
    tags: ['Esports', 'PC', 'Console'],
    members: [],
    visibility: 'public',
    location: 'Bangalore',
    ownerId: 'admin',
    founderName: 'Ajay Singh',
    founderBio: 'Gaming is not a crime, it is a lifestyle of the future.'
  },
  {
    id: 'c20',
    name: 'App Designers',
    description: 'Designing delightful experiences. UI/UX critiques, case studies, and prototyping.',
    category: 'Design',
    memberCount: 1400,
    image: 'https://images.unsplash.com/photo-1569098644584-210bcd375b59',
    coverImage: 'https://images.unsplash.com/photo-1569098644584-210bcd375b59',
    tags: ['UI', 'UX', 'Product'],
    members: [],
    visibility: 'public',
    location: 'Bangalore',
    ownerId: 'u1',
    founderName: 'Jatin Oberoi',
    founderBio: 'Design is not just how it looks, but how it works and feels.'
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: 'e1',
    clubId: 'c5',
    title: 'AI Builders',
    description: 'Bring your laptop and your best ideas. Pizza provided! We will be building AI agents from scratch.',
    date: '2023-11-15T18:00:00',
    location: 'TechHub Downtown, Bangalore',
    image: 'https://plus.unsplash.com/premium_photo-1683121710572-7723bd2e235d',
    bannerImage: 'https://plus.unsplash.com/premium_photo-1683121710572-7723bd2e235d',
    capacity: 100,
    attendees: 42,
    rsvps: { 'u1': 'going', 'm1': 'going', 'm2': 'maybe' }
  },
  {
    id: 'e2',
    clubId: 'c20',
    title: 'Design Critique Session',
    description: 'Get feedback on your portfolio from senior designers. Bring your case studies.',
    date: '2023-11-20T19:00:00',
    location: 'Creative Loft, Bangalore',
    image: 'https://picsum.photos/seed/design/400/300',
    bannerImage: 'https://picsum.photos/seed/design-banner/1200/400',
    capacity: 30,
    attendees: 15,
    rsvps: { 'm3': 'going' }
  },
  {
    id: 'e3',
    clubId: 'c2',
    title: 'Sunrise 10K',
    description: 'Early morning run through the city gardens. Pace group 5:30/km.',
    date: '2023-11-22T06:00:00',
    location: 'Cubbon Park, Bangalore',
    image: 'https://picsum.photos/seed/morningrun/400/300',
    bannerImage: 'https://picsum.photos/seed/run-banner/1200/400',
    capacity: 200,
    attendees: 85,
    rsvps: {}
  }
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'p1',
    clubId: 'c5',
    user: MOCK_USER,
    content: 'Just shipped my first React app! Thanks for the help everyone.',
    likes: 24,
    timestamp: '2 hours ago',
  }
];

export const MOCK_NOTIFICATIONS: Notification[] = [
    {
        id: 'n1',
        userId: 'u1',
        type: 'EVENT_INVITE',
        message: 'The Book Nook invited you to "Classic Sci-Fi Night"',
        read: false,
        timestamp: '10 mins ago',
        linkId: 'c1',
        viewToNavigate: 'CLUB_DETAIL' as any
    },
    {
        id: 'n2',
        userId: 'u1',
        type: 'NEW_POST',
        message: 'New discussion in Code & Coffee: "Thoughts on Gemini 2.0?"',
        read: false,
        timestamp: '1 hour ago',
        linkId: 'c5',
        viewToNavigate: 'CLUB_DETAIL' as any
    },
    {
        id: 'n3',
        userId: 'u1',
        type: 'RSVP_UPDATE',
        message: 'Your spot is confirmed for "Late Night Hackathon"',
        read: true,
        timestamp: '1 day ago',
        linkId: 'e1',
        viewToNavigate: 'EVENT_DETAIL' as any
    }
];